services:
  - type: web
    name: secureye
    runtime: static
    staticPublishPath: .
    buildCommand: ""
    routes:
      - type: rewrite
        source: /docs
        destination: /docs.html
      - type: rewrite
        source: /verify
        destination: /verify.html
      - type: rewrite
        source: /*
        destination: /index.html
